.mode columns
.headers on
PRAGMA foreign_keys = ON;


/*LISTAR CLIENTES POR ORDEM  ALFABETICA*/
.width 8 20
SELECT DISTINCT PESSOA.nome 
FROM PESSOA 
INNER JOIN CLIENTE 
ON PESSOA.idPessoa=CLIENTE.idCliente 
ORDER BY PESSOA.nome ASC;


/*LISTAR FUNCIONARIOS*/
SELECT DISTINCT PESSOA.nome 
FROM PESSOA 
INNER JOIN FUNCIONARIO 
ON PESSOA.idPessoa=FUNCIONARIO.idFuncionario;

/*LISTAR COMBOIOS*/
SELECT DISTINCT COMBOIO.id, COMBOIO.tipo 
FROM COMBOIO;

/*LISTAR OCORRENCIAS*/
SELECT DISTINCT OCORRENCIA.hora, COMBOIO.dataOcorr 
FROM OCORRENCIA;

/*LISTAR ITINERARIOS*/
SELECT DISTINCT ITINERARIO.codigo,ITINERARIO.nOcorrencias 
FROM ITINERARIO;

/*LISTAR ESTACOES*/
SELECT DISTINCT ESTACAO.nome 
FROM ESTACAO;

/*LISTAR CIDADES*/
SELECT DISTINCT CIDADE.nome 
FROM CIDADE;

/*LISTAR BILHETES*/
SELECT DISTINCT BILHETE.preco, BILHETE.dataCompra 
FROM BILHETE;

/*LISTA DE CLIENTES COM NECESSIDADES ESPECIAIS*/
SELECT DISTINCT PESSOA.nome 
FROM PESSOA 
INNER JOIN CLIENTE 
ON PESSOA.idPessoa=CLIENTE.idCliente 
AND CLIENTE.necessidadesEspeciais='TRUE';

/*SALARIO MEDIO DOS FUNCIONARIO*/
SELECT AVG(FUNCIONARIO.salario) 
FROM FUNCIONARIO;

/*LISTAR OS SALARIOS DOS FUNCIONARIOS*/
SELECT PESSOA.nome, FUNCIONARIO.salario 
FROM PESSOA 
INNER JOIN FUNCIONARIO 
ON PESSOA.idPessoa=FUNCIONARIO.idFuncionario;

/*BILHETES ORDENADOS POR PRECO (MENOR-MAIOR)*/
SELECT BILHETE.preco 
FROM BILHETE 
ORDER BY BILHETE.preco ASC;

/*OBTER OS 5 BILHETES MAIS CAROS*/
SELECT BILHETE.preco
 FROM BILHETE 
 ORDER BY BILHETE.preco 
 DESC LIMIT 5;

/*PESQUISA DE PESSOA POR NIF COM OS NUMEROS X*/
SELECT DISTINCT PESSOA.nif, PESSOA.nome 
FROM PESSOA 
WHERE PESSOA.nif 
LIKE '1%';

/*NUMERO DE OCORRENCIAS DE 1 ITINERARIO NUM DIA EM MEDIA*/
/*NUMERO DE CLIENTES POR COMBOIO POR ITINERARIO EM MEDIA*/
/*LISTA DE FUNCIONARIOS POR ESTACAO*/
/*LISTA DE FUNCIONARIOS POR FUNCOES*/
/*VALOR MÉDIO DOS BILHETES POR ITINERARIO NUM DIA*/


/*USAR DATAS*/
/*LUCRO DIARIO DE 1 ITINERARIO*/
/*TIPO DE COMBOIO MAIS COMUM NUMA ESTACAO*/


/*FUNCIONARIOS QUE TAMBEM SAO CLIENTES*/
SELECT * FROM PESSOA 
INNER JOIN CLIENTE 
ON PESSOA.idPessoa=CLIENTE.idCliente 
INNER JOIN FUNCIONARIO 
ON PESSOA.idPESSOA=FUNCIONARIO.idFuncionario;

